In [2]:
from matplotlib import pyplot as plt
from scipy.stats import linregress
import numpy as np
from sklearn import datasets
import pandas as pd

In [5]:
week_1_df = pd.read_csv('../base_datasets/tracking_week_1.csv')
week_1_df.head()

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event
0,2022090800,56,35472.0,Rodger Saffold,1,2022-09-08 20:24:05.200000,76.0,BUF,left,88.37,27.27,1.62,1.15,0.16,231.74,147.90,NaN
1,2022090800,56,35472.0,Rodger Saffold,2,2022-09-08 20:24:05.299999,76.0,BUF,left,88.47,27.13,1.67,0.61,0.17,230.98,148.53,pass_arrived
2,2022090800,56,35472.0,Rodger Saffold,3,2022-09-08 20:24:05.400000,76.0,BUF,left,88.56,27.01,1.57,0.49,0.15,230.98,147.05,NaN
3,2022090800,56,35472.0,Rodger Saffold,4,2022-09-08 20:24:05.500000,76.0,BUF,left,88.64,26.90,1.44,0.89,0.14,232.38,145.42,NaN
4,2022090800,56,35472.0,Rodger Saffold,5,2022-09-08 20:24:05.599999,76.0,BUF,left,88.72,26.80,1.29,1.24,0.13,233.36,141.95,NaN

In [6]:
week_1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1407439 entries, 0 to 1407438
Data columns (total 17 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   gameId         1407439 non-null  int64
 1   playId         1407439 non-null  int64
 2   nflId          1346246 non-null  float64
 3   displayName    1407439 non-null  object
 4   frameId        1407439 non-null  int64
 5   time           1407439 non-null  object
 6   jerseyNumber   1346246 non-null  float64
 7   club           1407439 non-null  object
 8   playDirection  1407439 non-null  object
 9   x              1407439 non-null  float64
 10  y              1407439 non-null  float64
 11  s              1407439 non-null  float64
 12  a              1407439 non-null  float64
 13  dis            1407439 non-null  float64
 14  o              1346397 non-null  float64
 15  dir            1346397 non-null  float64
 16  event          130268 non-null   object
dtypes: float64(9), int64(3), object(5)
memory usage: 182.5+ MB

In [9]:
week_1_df['jerseyNumber'] = df['jerseyNumber'].astype(int)

(1407439, 17)

In [20]:
cle_week_1_df = week_1_df.loc[(week_1_df['club'] == 'CLE')]
Nick_chubb_df = cle_week_1_df.loc[cle_week_1_df['displayName'] == 'Nick Chubb']
Nick_chubb_df.tail(60)
#cle_week_1_df.head(40)

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event
256211,2022091101,3669,46104.0,Nick Chubb,20,2022-09-11 15:55:37.799999,24.0,CLE,left,72.52,30.69,5.52,1.57,0.55,313.00,319.28,handoff
256212,2022091101,3669,46104.0,Nick Chubb,21,2022-09-11 15:55:37.900000,24.0,CLE,left,72.16,31.11,5.63,1.05,0.56,310.47,318.86,NaN
256213,2022091101,3669,46104.0,Nick Chubb,22,2022-09-11 15:55:38.000000,24.0,CLE,left,71.79,31.54,5.73,0.65,0.57,315.40,318.50,NaN
256214,2022091101,3669,46104.0,Nick Chubb,23,2022-09-11 15:55:38.099999,24.0,CLE,left,71.40,31.99,5.91,0.45,0.59,318.70,318.98,NaN
256215,2022091101,3669,46104.0,Nick Chubb,24,2022-09-11 15:55:38.200000,24.0,CLE,left,71.00,32.50,6.01,0.40,0.65,338.86,320.62,NaN
256216,2022091101,3669,46104.0,Nick Chubb,25,2022-09-11 15:55:38.299999,24.0,CLE,left,70.62,32.97,5.98,0.74,0.60,344.35,321.02,NaN
256217,2022091101,3669,46104.0,Nick Chubb,26,2022-09-11 15:55:38.400000,24.0,CLE,left,70.31,33.42,5.93,1.19,0.55,336.27,323.82,NaN
256218,2022091101,3669,46104.0,Nick Chubb,27,2022-09-11 15:55:38.500000,24.0,CLE,left,69.97,33.90,5.86,1.38,0.59,339.74,324.90,NaN
256219,2022091101,3669,46104.0,Nick Chubb,28,2022-09-11 15:55:38.599999,24.0,CLE,left,69.64,34.38,5.77,1.52,0.58,345.75,326.01,first_contact
256220,2022091101,3669,46104.0,Nick Chubb,29,2022-09-11 15:55:38.700000,24.0,CLE,left,69.53,34.86,5.30,2.85,0.50,352.26,333.55,NaN
256221,2022091101,3669,46104.0,Nick Chubb,30,2022-09-11 15:55:38.799999,24.0,CLE,left,69.48,35.22,4.46,4.22,0.36,3.14,340.00,NaN
256222,2022091101,3669,46104.0,Nick Chubb,31,2022-09-11 15:55:38.900000,24.0,CLE,left,69.35,35.60,3.99,4.74,0.40,354.89,342.79,NaN
256223,2022091101,3669,46104.0,Nick Chubb,32,2022-09-11 15:55:39.000000,24.0,CLE,left,69.25,35.96,3.53,4.99,0.38,347.98,344.95,NaN
256224,2022091101,3669,46104.0,Nick Chubb,33,2022-09-11 15:55:39.099999,24.0,CLE,left,69.17,36.29,3.09,4.83,0.34,343.60,347.82,NaN
256225,2022091101,3669,46104.0,Nick Chubb,34,2022-09-11 15:55:39.200000,24.0,CLE,left,69.14,36.62,2.73,4.52,0.33,336.40,350.65,NaN
256226,2022091101,3669,46104.0,Nick Chubb,35,2022-09-11 15:55:39.299999,24.0,CLE,left,69.12,36.96,2.44,4.06,0.34,328.75,353.24,NaN
256227,2022091101,3669,46104.0,Nick Chubb,36,2022-09-11 15:55:39.400000,24.0,CLE,left,69.09,37.26,2.19,3.30,0.30,322.37,354.68,NaN
256228,2022091101,3669,46104.0,Nick Chubb,37,2022-09-11 15:55:39.500000,24.0,CLE,left,69.05,37.48,1.90,2.71,0.22,320.10,355.02,NaN
256229,2022091101,3669,46104.0,Nick Chubb,38,2022-09-11 15:55:39.599999,24.0,CLE,left,69.03,37.66,1.67,2.95,0.18,332.93,356.33,NaN
256230,2022091101,3669,46104.0,Nick Chubb,39,2022-09-11 15:55:39.700000,24.0,CLE,left,69.00,37.84,1.44,2.90,0.18,330.68,355.54,NaN
256231,2022091101,3669,46104.0,Nick Chubb,40,2022-09-11 15:55:39.799999,24.0,CLE,left,68.99,37.97,1.18,2.37,0.13,346.25,355.79,NaN
256232,2022091101,3669,46104.0,Nick Chubb,41,2022-09-11 15:55:39.900000,24.0,CLE,left,68.94,38.09,1.01,1.90,0.14,342.83,351.74,NaN
256233,2022091101,3669,46104.0,Nick Chubb,42,2022-09-11 15:55:40.000000,24.0,CLE,left,68.93,38.18,0.84,1.57,0.09,354.76,349.31,NaN
256234,2022091101,3669,46104.0,Nick Chubb,43,2022-09-11 15:55:40.099999,24.0,CLE,left,68.86,38.29,0.81,1.24,0.12,349.78,338.57,NaN
256235,2022091101,3669,46104.0,Nick Chubb,44,2022-09-11 15:55:40.200000,24.0,CLE,left,68.83,38.36,0.70,1.21,0.08,358.86,333.59,tackle
256236,2022091101,3669,46104.0,Nick Chubb,45,2022-09-11 15:55:40.299999,24.0,CLE,left,68.80,38.41,0.59,1.18,0.06,358.86,330.40,NaN
256237,2022091101,3669,46104.0,Nick Chubb,46,2022-09-11 15:55:40.400000,24.0,CLE,left,68.60,38.52,0.70,1.37,0.23,337.33,315.46,NaN
256238,2022091101,3669,46104.0,Nick Chubb,47,2022-09-11 15:55:40.500000,24.0,CLE,left,68.48,38.61,0.65,1.42,0.14,310.79,311.65,NaN
256239,2022091101,3669,46104.0,Nick Chubb,48,2022-09-11 15:55:40.599999,24.0,CLE,left,68.36,38.73,0.60,1.43,0.17,300.56,311.85,NaN
257112,2022091101,3707,46104.0,Nick Chubb,1,2022-09-11 15:56:47.099999,24.0,CLE,left,75.98,20.61,6.03,1.93,0.61,298.67,183.80,NaN
257113,2022091101,3707,46104.0,Nick Chubb,2,2022-09-11 15:56:47.200000,24.0,CLE,left,75.87,20.00,5.92,2.12,0.62,308.05,187.03,NaN
257114,2022091101,3707,46104.0,Nick Chubb,3,2022-09-11 15:56:47.299999,24.0,CLE,left,75.79,19.43,5.73,2.24,0.58,317.54,188.03,NaN
257115,2022091101,3707,46104.0,Nick Chubb,4,2022-09-11 15:56:47.400000,24.0,CLE,left,75.56,18.78,5.93,2.25,0.69,323.66,193.24,NaN
257116,2022091101,3707,46104.0,Nick Chubb,5,2022-09-11 15:56:47.500000,24.0,CLE,left,75.40,18.26,5.68,3.18,0.55,318.02,196.92,pass_arrived
257117,2022091101,3707,46104.0,Nick Chubb,6,2022-09-11 15:56:47.599999,24.0,CLE,left,75.22,17.73,5.48,3.87,0.56,306.40,201.44,pass_outcome_caught
257118,2022091101,3707,46104.0,Nick Chubb,7,2022-09-11 15:56:47.700000,24.0,CLE,left,75.02,17.23,5.27,4.48,0.54,296.82,206.37,NaN
257119,2022091101,3707,46104.0,Nick Chubb,8,2022-09-11 15:56:47.799999,24.0,CLE,left,74.78,16.76,5.03,5.32,0.52,286.03,213.45,NaN
257120,2022091101,3707,46104.0,Nick Chubb,9,2022-09-11 15:56:47.900000,24.0,CLE,left,74.49,16.36,4.85,5.07,0.49,278.19,218.27,NaN
257121,2022091101,3707,46104.0,Nick Chubb,10,2022-09-11 15:56:48.000000,24.0,CLE,left,74.18,16.00,4.72,4.46,0.47,254.20,223.64,NaN
257122,2022091101,3707,46104.0,Nick Chubb,11,2022-09-11 15:56:48.099999,24.0,CLE,left,73.85,15.68,4.69,4.26,0.46,239.40,230.90,NaN
257123,2022091101,3707,46104.0,Nick Chubb,12,2022-09-11 15:56:48.200000,24.0,CLE,left,73.46,15.40,4.84,3.69,0.48,229.35,236.23,NaN
257124,2022091101,3707,46104.0,Nick Chubb,13,2022-09-11 15:56:48.299999,24.0,CLE,left,73.03,15.15,4.93,3.50,0.49,225.45,242.55,NaN
257125,2022091101,3707,46104.0,Nick Chubb,14,2022-09-11 15:56:48.400000,24.0,CLE,left,72.58,14.93,5.07,2.81,0.51,223.06,245.41,NaN
257126,2022091101,3707,46104.0,Nick Chubb,15,2022-09-11 15:56:48.500000,24.0,CLE,left,72.12,14.69,5.19,1.69,0.52,220.38,244.97,NaN
257127,2022091101,3707,46104.0,Nick Chubb,16,2022-09-11 15:56:48.599999,24.0,CLE,left,71.64,14.46,5.27,0.66,0.52,221.58,244.74,NaN
257128,2022091101,3707,46104.0,Nick Chubb,17,2022-09-11 15:56:48.700000,24.0,CLE,left,71.16,14.22,5.38,0.32,0.54,222.87,243.09,NaN
257129,2022091101,3707,46104.0,Nick Chubb,18,2022-09-11 15:56:48.799999,24.0,CLE,left,70.69,13.96,5.45,1.06,0.54,221.61,240.73,NaN
257130,2022091101,3707,46104.0,Nick Chubb,19,2022-09-11 15:56:48.900000,24.0,CLE,left,70.22,13.67,5.56,1.77,0.55,212.72,237.82,NaN
257131,2022091101,3707,46104.0,Nick Chubb,20,2022-09-11 15:56:49.000000,24.0,CLE,left,69.74,13.34,5.79,2.27,0.58,216.76,234.47,NaN
257132,2022091101,3707,46104.0,Nick Chubb,21,2022-09-11 15:56:49.099999,24.0,CLE,left,69.27,12.99,5.93,2.22,0.59,207.75,231.97,first_contact
257133,2022091101,3707,46104.0,Nick Chubb,22,2022-09-11 15:56:49.200000,24.0,CLE,left,68.81,12.61,5.99,1.93,0.60,205.82,230.00,NaN
257134,2022091101,3707,46104.0,Nick Chubb,23,2022-09-11 15:56:49.299999,24.0,CLE,left,68.34,12.19,6.17,1.82,0.63,199.91,227.65,NaN
257135,2022091101,3707,46104.0,Nick Chubb,24,2022-09-11 15:56:49.400000,24.0,CLE,left,67.88,11.77,6.24,1.43,0.63,193.52,226.54,NaN
257136,2022091101,3707,46104.0,Nick Chubb,25,2022-09-11 15:56:49.500000,24.0,CLE,left,67.42,11.34,6.22,1.08,0.62,189.63,226.00,NaN
257137,2022091101,3707,46104.0,Nick Chubb,26,2022-09-11 15:56:49.599999,24.0,CLE,left,66.98,10.91,6.14,1.15,0.62,185.36,225.12,NaN
257138,2022091101,3707,46104.0,Nick Chubb,27,2022-09-11 15:56:49.700000,24.0,CLE,left,66.57,10.49,5.93,1.64,0.59,183.54,224.27,tackle
257139,2022091101,3707,46104.0,Nick Chubb,28,2022-09-11 15:56:49.799999,24.0,CLE,left,66.16,10.07,5.75,2.05,0.58,183.54,223.68,NaN
257140,2022091101,3707,46104.0,Nick Chubb,29,2022-09-11 15:56:49.900000,24.0,CLE,left,65.81,9.69,5.33,3.11,0.52,173.56,222.95,NaN
257141,2022091101,3707,46104.0,Nick Chubb,30,2022-09-11 15:56:50.000000,24.0,CLE,left,65.50,9.34,4.61,4.37,0.46,159.14,221.54,NaN
257142,2022091101,3707,46104.0,Nick Chubb,31,2022-09-11 15:56:50.099999,24.0,CLE,left,65.25,9.06,3.84,4.97,0.38,149.28,221.08,NaN

In [28]:
cle_week_1_3707_df = week_1_df.loc[(week_1_df['playId'] == 3707)]
cle_week_1_3707_df.head(40)

,gameId,playId,nflId,displayName,frameId,time,jerseyNumber,club,playDirection,x,y,s,a,dis,o,dir,event
256864,2022091101,3707,41264.0,Joel Bitonio,1,2022-09-11 15:56:47.099999,75.0,CLE,left,72.30,24.94,2.47,1.23,0.25,249.66,135.77,NaN
256865,2022091101,3707,41264.0,Joel Bitonio,2,2022-09-11 15:56:47.200000,75.0,CLE,left,72.46,24.76,2.35,1.52,0.24,246.78,139.00,NaN
256866,2022091101,3707,41264.0,Joel Bitonio,3,2022-09-11 15:56:47.299999,75.0,CLE,left,72.58,24.54,2.33,1.87,0.25,244.98,147.43,NaN
256867,2022091101,3707,41264.0,Joel Bitonio,4,2022-09-11 15:56:47.400000,75.0,CLE,left,72.68,24.31,2.37,2.13,0.25,246.33,156.20,NaN
256868,2022091101,3707,41264.0,Joel Bitonio,5,2022-09-11 15:56:47.500000,75.0,CLE,left,72.73,24.06,2.43,2.43,0.26,252.48,166.02,pass_arrived
256869,2022091101,3707,41264.0,Joel Bitonio,6,2022-09-11 15:56:47.599999,75.0,CLE,left,72.76,23.81,2.46,2.24,0.25,250.58,173.51,pass_outcome_caught
256870,2022091101,3707,41264.0,Joel Bitonio,7,2022-09-11 15:56:47.700000,75.0,CLE,left,72.75,23.52,2.65,2.14,0.28,238.31,181.54,NaN
256871,2022091101,3707,41264.0,Joel Bitonio,8,2022-09-11 15:56:47.799999,75.0,CLE,left,72.72,23.24,2.79,1.93,0.29,234.93,186.99,NaN
256872,2022091101,3707,41264.0,Joel Bitonio,9,2022-09-11 15:56:47.900000,75.0,CLE,left,72.67,22.93,2.98,1.63,0.31,234.93,191.00,NaN
256873,2022091101,3707,41264.0,Joel Bitonio,10,2022-09-11 15:56:48.000000,75.0,CLE,left,72.60,22.62,3.12,1.29,0.32,234.93,194.43,NaN
256874,2022091101,3707,41264.0,Joel Bitonio,11,2022-09-11 15:56:48.099999,75.0,CLE,left,72.50,22.28,3.29,1.02,0.35,228.17,196.82,NaN
256875,2022091101,3707,41264.0,Joel Bitonio,12,2022-09-11 15:56:48.200000,75.0,CLE,left,72.38,21.95,3.38,0.97,0.35,222.37,199.54,NaN
256876,2022091101,3707,41264.0,Joel Bitonio,13,2022-09-11 15:56:48.299999,75.0,CLE,left,72.25,21.59,3.53,0.84,0.38,218.72,200.43,NaN
256877,2022091101,3707,41264.0,Joel Bitonio,14,2022-09-11 15:56:48.400000,75.0,CLE,left,72.08,21.21,3.74,0.87,0.42,208.89,202.97,NaN
256878,2022091101,3707,41264.0,Joel Bitonio,15,2022-09-11 15:56:48.500000,75.0,CLE,left,71.92,20.84,3.78,1.02,0.40,206.35,203.92,NaN
256879,2022091101,3707,41264.0,Joel Bitonio,16,2022-09-11 15:56:48.599999,75.0,CLE,left,71.76,20.48,3.80,1.17,0.40,204.47,204.43,NaN
256880,2022091101,3707,41264.0,Joel Bitonio,17,2022-09-11 15:56:48.700000,75.0,CLE,left,71.57,20.09,3.89,1.19,0.43,210.05,205.23,NaN
256881,2022091101,3707,41264.0,Joel Bitonio,18,2022-09-11 15:56:48.799999,75.0,CLE,left,71.39,19.71,3.92,1.22,0.42,208.28,205.33,NaN
256882,2022091101,3707,41264.0,Joel Bitonio,19,2022-09-11 15:56:48.900000,75.0,CLE,left,71.21,19.36,3.83,1.35,0.40,208.28,206.29,NaN
256883,2022091101,3707,41264.0,Joel Bitonio,20,2022-09-11 15:56:49.000000,75.0,CLE,left,71.03,19.01,3.78,1.41,0.40,207.18,207.02,NaN
256884,2022091101,3707,41264.0,Joel Bitonio,21,2022-09-11 15:56:49.099999,75.0,CLE,left,70.83,18.66,3.77,1.51,0.40,204.79,208.41,first_contact
256885,2022091101,3707,41264.0,Joel Bitonio,22,2022-09-11 15:56:49.200000,75.0,CLE,left,70.65,18.31,3.71,1.54,0.39,204.79,208.38,NaN
256886,2022091101,3707,41264.0,Joel Bitonio,23,2022-09-11 15:56:49.299999,75.0,CLE,left,70.47,17.98,3.63,1.55,0.38,204.79,208.77,NaN
256887,2022091101,3707,41264.0,Joel Bitonio,24,2022-09-11 15:56:49.400000,75.0,CLE,left,70.30,17.66,3.51,1.70,0.37,205.97,209.02,NaN
256888,2022091101,3707,41264.0,Joel Bitonio,25,2022-09-11 15:56:49.500000,75.0,CLE,left,70.11,17.33,3.48,1.57,0.37,205.97,209.52,NaN
256889,2022091101,3707,41264.0,Joel Bitonio,26,2022-09-11 15:56:49.599999,75.0,CLE,left,69.93,17.03,3.40,1.53,0.35,209.35,210.56,NaN
256890,2022091101,3707,41264.0,Joel Bitonio,27,2022-09-11 15:56:49.700000,75.0,CLE,left,69.74,16.75,3.28,1.62,0.34,210.53,212.78,tackle
256891,2022091101,3707,41264.0,Joel Bitonio,28,2022-09-11 15:56:49.799999,75.0,CLE,left,69.56,16.48,3.13,1.83,0.32,210.53,214.49,NaN
256892,2022091101,3707,41264.0,Joel Bitonio,29,2022-09-11 15:56:49.900000,75.0,CLE,left,69.38,16.24,2.94,2.04,0.30,211.72,216.69,NaN
256893,2022091101,3707,41264.0,Joel Bitonio,30,2022-09-11 15:56:50.000000,75.0,CLE,left,69.21,16.01,2.79,2.04,0.29,211.01,218.22,NaN
256894,2022091101,3707,41264.0,Joel Bitonio,31,2022-09-11 15:56:50.099999,75.0,CLE,left,69.03,15.80,2.63,2.01,0.28,211.01,219.85,NaN
256895,2022091101,3707,42347.0,Amari Cooper,1,2022-09-11 15:56:47.099999,2.0,CLE,left,64.63,3.74,5.76,2.00,0.58,247.37,229.11,NaN
256896,2022091101,3707,42347.0,Amari Cooper,2,2022-09-11 15:56:47.200000,2.0,CLE,left,64.19,3.37,5.71,1.91,0.58,250.30,231.12,NaN
256897,2022091101,3707,42347.0,Amari Cooper,3,2022-09-11 15:56:47.299999,2.0,CLE,left,63.74,3.02,5.61,1.82,0.57,251.91,232.72,NaN
256898,2022091101,3707,42347.0,Amari Cooper,4,2022-09-11 15:56:47.400000,2.0,CLE,left,63.27,2.72,5.51,2.23,0.56,251.91,236.59,NaN
256899,2022091101,3707,42347.0,Amari Cooper,5,2022-09-11 15:56:47.500000,2.0,CLE,left,62.80,2.44,5.40,2.47,0.55,256.20,239.86,pass_arrived
256900,2022091101,3707,42347.0,Amari Cooper,6,2022-09-11 15:56:47.599999,2.0,CLE,left,62.32,2.19,5.30,2.47,0.54,264.82,242.57,pass_outcome_caught
256901,2022091101,3707,42347.0,Amari Cooper,7,2022-09-11 15:56:47.700000,2.0,CLE,left,61.84,1.97,5.20,2.58,0.53,281.18,245.98,NaN
256902,2022091101,3707,42347.0,Amari Cooper,8,2022-09-11 15:56:47.799999,2.0,CLE,left,61.36,1.79,5.06,2.88,0.51,286.73,250.02,NaN
256903,2022091101,3707,42347.0,Amari Cooper,9,2022-09-11 15:56:47.900000,2.0,CLE,left,60.89,1.63,4.96,2.88,0.50,290.77,252.87,NaN

In [30]:
cle_week_1_3707_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 713 entries, 256864 to 257576
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gameId         713 non-null    int64
 1   playId         713 non-null    int64
 2   nflId          682 non-null    float64
 3   displayName    713 non-null    object
 4   frameId        713 non-null    int64
 5   time           713 non-null    object
 6   jerseyNumber   682 non-null    float64
 7   club           713 non-null    object
 8   playDirection  713 non-null    object
 9   x              713 non-null    float64
 10  y              713 non-null    float64
 11  s              713 non-null    float64
 12  a              713 non-null    float64
 13  dis            713 non-null    float64
 14  o              682 non-null    float64
 15  dir            682 non-null    float64
 16  event          92 non-null     object
dtypes: float64(9), int64(3), object(5)
memory usage: 100.3+ KB

In [37]:
#cle_week_1_3707_df['displayName'].nunique()
unique_values = cle_week_1_3707_df['displayName'].unique()
#unique_values = unique_values.reset_index()
#unique_values.info()
unique_values, counts = np.unique(unique_values , return_counts=True)

# Display unique values and their counts
for value, count in zip(unique_values, counts):
    print(f"Value: {value}, Count: {count}")

Value: Amari Cooper, Count: 1
Value: Bravvion Roy, Count: 1
Value: Brian Burns, Count: 1
Value: Donovan Peoples-Jones, Count: 1
Value: Donte Jackson, Count: 1
Value: Ethan Pocic, Count: 1
Value: Frankie Luvu, Count: 1
Value: Harrison Bryant, Count: 1
Value: Jacoby Brissett, Count: 1
Value: James Hudson, Count: 1
Value: Jaycee Horn, Count: 1
Value: Jedrick Wills, Count: 1
Value: Jeremy Chinn, Count: 1
Value: Joel Bitonio, Count: 1
Value: Matt Ioannidis, Count: 1
Value: Michael Dunn, Count: 1
Value: Myles Hartsfield, Count: 1
Value: Nick Chubb, Count: 1
Value: Shaq Thompson, Count: 1
Value: Wyatt Teller, Count: 1
Value: Xavier Woods, Count: 1
Value: Yetur Gross-Matos, Count: 1
Value: football, Count: 1

In [11]:
columns_to_drop = ['gameId', 'club']
cle_week_1_df_copy=cle_week_1_df.copy

In [7]:
play_85_df=cle_week_1_df.loc[cle_week_1_df['playId'] == 85, ['displayName','time',]]
play_85_df.head()

             displayName                        time
172799  Jadeveon Clowney  2022-09-11 13:05:42.500000
172800  Jadeveon Clowney  2022-09-11 13:05:42.599999
172801  Jadeveon Clowney  2022-09-11 13:05:42.700000
172802  Jadeveon Clowney  2022-09-11 13:05:42.799999
172803  Jadeveon Clowney  2022-09-11 13:05:42.900000

In [8]:
play_85_df.nunique()

displayName    11
time           26
dtype: int64